version: '3'
services:

  web_server:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    entrypoint: "bin/setup"
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.6.6-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data

  redis:
    image: redis:3.2.11-alpine
    volumes:
      - ./.redis:/data

